### ISSUE TITLE
Missing "share link" in nextcloud 15 when app enabled

### ISSUE THREAD

**Issue by muppeth** [nextcloud/socialsharing#32] opened 2019-01-23 10:24 UTC
When social sharing app enabled (doesnt matter if only email, facebook or all of them) the "Share Link" button disappears. Disabling the app brings back the button.
https://help.nextcloud.com/t/feature-ui-where-sharing-link-in-nextcloud-14/38430

**Comment by juliushaertl** [comment] 2019-01-23 10:58
Duplicate of https://github.com/nextcloud/socialsharing/issues/29. Will be fixed with the next server release.

**Closed by juliushaertl** 2019-01-23 10:58 UTC
